services:
  rssaggregator-app:
    container_name: RssAggregatorApp
    build: ../RssAggregator/
    ports:
      - 5183:5000
    networks:
      - net
    depends_on:
      rssaggregator-db:
        condition: "service_healthy"
  rssaggregator-db:
    container_name: RssAggregatorDb
    image: postgres
    expose:
      - 5432
    networks:
      - net
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RssAggregatorDatabase
    volumes:
      - rssaggregator-db-data:/var/lib/postgres/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "RssAggregatorDatabase" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
  adminer:
    container_name: RssAggregatorDb-Adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - rssaggregator-db
networks:
  net:
    driver: bridge
volumes:
  rssaggregator-db-data: