services:
  rssaggregator-db-development:
    container_name: RssAggregatorDbDev
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RssAggregatorDatabase
    volumes:
      - rssaggregator-db-data:/var/lib/postgres/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  adminer-local:
    container_name: RssAggregatorDbDev-Adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - rssaggregator-db-development
volumes:
  rssaggregator-db-data: