services:
  rssaggregator-db-development:
    container_name: RssAggregatorDbDev
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RssAggregatorDatabase
    volumes:
      - rssaggregator-db-data:/var/lib/postgres/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer-local:
    container_name: RssAggregatorDbDev-Adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - rssaggregator-db-development

  loki:
    container_name: RssAggregatorLoki
    image: grafana/loki:3.3.0
    ports:
      - 3100:3100
    volumes:
      - ./config/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  otel-collector:
    container_name: RssAggregatorOTelCollector
    image: otel/opentelemetry-collector-contrib:0.116.1
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
    depends_on:
      - loki
    networks:
      - monitoring

  grafana:
    container_name: RssAggregatorGrafana
    image: grafana/grafana:latest-ubuntu
    ports:
      - 3000:3000
    volumes:
      - rssaggregator-grafana:/var/lib/grafana
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    depends_on:
      - loki
      - otel-collector
    networks:
      - monitoring

volumes:
  rssaggregator-db-data:
  rssaggregator-grafana:

networks:
  monitoring: